# Generated by Django 5.1.7 on 2025-03-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0002_campanha'),
        ('lideranca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lideranca',
            name='campanha',
        ),
        migrations.AddField(
            model_name='lideranca',
            name='campanhas',
            field=models.ManyToManyField(related_name='liderancas', to='campanha.campanha'),
        ),
    ]
