# Generated by Django 5.1.7 on 2025-03-27 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lideranca', '0002_remove_lideranca_campanha_lideranca_campanhas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lideranca',
            name='metas',
        ),
    ]
