# Generated by Django 5.1.7 on 2025-03-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='created_by',
            new_name='coordenador',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('conflitante', 'Conflitante')], max_length=50),
        ),
    ]
