# Generated by Django 5.1.7 on 2025-03-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoAudiovisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('data_publicacao', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('video', 'Vídeo'), ('fotografia', 'Fotografia')], max_length=50)),
            ],
        ),
    ]
